library(grid)
library(png)
library(gridExtra)

png(filename = 'projects/venn.png',width = 1200,height = 800)
print(vennDiagram(dat.venn, circle.col = col,cex = c(3,3,3)))
dev.off()
png(filename = 'projects/bar.png',width = 1200,height = 800)
print(bar.plot)
dev.off()
png(filename = 'projects/density.png',width = 1200,height = 800)
print(density.plot)
dev.off()

img <- readPNG('projects/bar.png')
g <- rasterGrob(img, interpolate=TRUE)
img <- readPNG('projects/density.png')
g1 <- rasterGrob(img,interpolate = TRUE)
img <- readPNG('projects/venn.png')
g2 <- rasterGrob(img,interpolate = TRUE)
pdf(file = 'projects/mpileup_summary_report2.pdf',width = 30,height = 20)
grid.arrange(g,g1,g2,ncol=2)
dev.off()